# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.2
_src_path: gh:algorandfoundation/algokit-python-template
author_email: sudoweezy@gmail.com
author_name: Stéphane
contract_name: digital_marketplace
deployment_language: python
preset_name: production
project_name: digital_marketplace-contracts

